version: "3"
services:
  twitteragentserver:
    image: twitteragentserver:latest
    volumes:
      - ./config:/project/config
    ports:
      - "3300:3300"
    stdin_open: true 
    tty: true
    environment:
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - HTTP_PORT:3300
    healthcheck:
      test: curl --fail http://localhost:3300/v1/info || exit 1
      interval: 60s
      timeout: 20s
      retries: 3
      start_period: 30s
    restart: unless-stopped